### ISSUE TITLE
Poczytaj sobie o tym: 

### ISSUE THREAD

**Issue by MikolajSzar** [ChrisAraneo/araneo-wordpress-theme#1]
https://github.com/ChrisAraneo/araneo-wordpress-theme/blob/6cc5caf9b3455df1accf7f0486a27789ed3beff6/src/styles/main.scss#L57

Poczytaj sobie o mobile first, o tej technice projektowania cssa: https://chcenawczoraj.pl/software/na-czym-polega-mobile-first-w-projektowaniu

**Comment by ChrisAraneo** [comment]
Strona co podesłałeś teraz się nie wczytuje, poczytam więcej o mobile first, dzięki
