### ISSUE TITLE
Linie 102-118 zrob inaczej

### ISSUE THREAD

**Issue by MikolajSzar** [ChrisAraneo/araneo-wordpress-theme#2]
https://github.com/ChrisAraneo/araneo-wordpress-theme/blob/6cc5caf9b3455df1accf7f0486a27789ed3beff6/src/styles/main.scss#L102

Użyj sobie benefitów SASSA:
https://stackoverflow.com/questions/10750563/after-and-before-pseudo-element-selectors-in-sass

**Comment by MikolajSzar** [comment]
Zrób mniej więcej tak:
.background-page {
    width: 100%;
    max-width: 100%;
&:before {
    content: "";
    position: absolute;
    width: 100%;
    max-width: 100%;
    height: 500px;
    background-color: transparent;
}
}
Wtedy korzystasz z dziedziczenia SASSowego

**Comment by ChrisAraneo** [comment]
Ok dzięki nie używałem tego ampersanda
